import type { Metadata } from "next";
import { Inter,Manrope } from "next/font/google";
import "./globals.css";

// COMPONENTS
import Header from "./components/Header";


// STYLES
import "./components/Header.css"
import "@/app/(auth)/login/login.css"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
        <Header/>
        {children}
        
        </body>
    </html>
  );
}
